### ISSUE TITLE
Convert NULL-cells to 0 cells

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/OSM_Events#1]
as @yair-grinb pointed out, NULL-cells are acutally 0 cells so we might change the data input for the map

**Comment by yair-grinb** [comment]
Clarifying, as I misunderstood @SlowMo24 - some cells are not included in the grid as they contained less than 20,000 entities, these are indeed NULL but do not appear in the data. 0 values are not NULL and this should be made clear with correct symbols.

**Comment by tyrasd** [comment]
this should be addressed with #2 and https://github.com/GIScience/OSM_Events/blob/gh-pages/index.html#L255, right?

**Comment by SlowMo24** [comment]
Sorry for the confusion, this statement was not very clear.

In a previous version, 8 cells had NULL values for all events (cell id: 3461, 6012, 6911, 6926, 7020, 8019, 8272, 9088). This was due to the 'left join' between the cell-geojson and the events.csv. These cells where present in the geojson but not in the events.csv. In a first version of the map, these cells where displayed as maximum event weight. @tyrasd then adapted this to display them as 0 event weight. @yair-grinb then confirmed that these cells are in fact 0 weight cells.

The issue here proposes to include these cells in the event.csv as 0 weight to not have to worry about the NULL handling and have clear and explicit data in and output. Please feel free to close this issue if the work-benefit balance is wrong.

**Comment by tyrasd** [comment]
Thanks for clarifying. I think the current solution is fine IMHO.
