### ISSUE TITLE
Add NONE-Cells

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/OSM_Events#2]
The cells visible on the interactive map are not space-covering as cells where ignored if the No of Nodes fell below a threshhold on quadtree seperation. I would propose to still show these cells as e.g. gray or striped to not confuse them with 0 cells. There should though be an option to not show them, if they distract the viewer.

If this issue is accepted (@yair-grinb ?):

@SlowMo24 can create the missing cells
@tyrasd could you adapt the code for Leaflet?

**Comment by SlowMo24** [comment]
I have added a globalNone.geojson to the gh-pages branch. It is one large multipolygon with "id":-1 where no cell was defined. If Leaflet does some internal indexing it might be better to split it into multiple polygons?

**Comment by tyrasd** [comment]
how does this look like:

<img src="https://user-images.githubusercontent.com/1927298/107681819-d9867680-6c9f-11eb-9422-d0aa5ac44d12.png" width="450px" />
<img src="https://user-images.githubusercontent.com/1927298/107681863-e99e5600-6c9f-11eb-978c-ee36d76b0f13.png" width="500px" />

(demo at https://tyrasd.github.io/OSM_Events/)

**Comment by yair-grinb** [comment]
This is nice and looks good when zooming-in. At lower zoom levels this may become a bit disorienting, any chance to make the lines less thick at lower zoom levels?

**Comment by tyrasd** [comment]
implemented in 9e065cd2cb1198e9dfec51761b978fc835ef84f7

**Comment by SlowMo24** [comment]
this looks great!!! For me a bit more space between the lines would work as well but thats just to get to 110%
