### ISSUE TITLE
Infobox on webmap

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/OSM_Events#4]
Please add a short info-box on the map

- [ ] so it can be found by search engines
- [x] it can shortly explain what can be seen here
- [x] it can link to the paper once a link is available

**Comment by tyrasd** [comment]
how does 2ec50c10425f97258f9034c6c06283ef9e15b1e0 look for now? Later we can add a link to the published paper

**Comment by tyrasd** [comment]
I just added links to the published paper in c9a06c2dda3508430ab33eb1c2b80d375aedfe02. Do you miss anything which should still be added?

**Comment by SlowMo24** [comment]
no, I currently don't, thanks
